import { v4 as uuid } from 'uuid'

export const TABLES_KEY = 'tables:library'
export const TABLES_VERSION = 1
export const MAX_HISTORY = 30

// Helper for compact starter-pack definitions: name, description, then
// each entry text as a string. All entries get default weight 1.
function pack(name, description, ...entries) {
  return {
    name,
    description,
    entries: entries.map((text) => ({ text })),
  }
}

export const STARTER_TABLES = [
  pack(
    'Random NPC quirk',
    'A quick mannerism to drop on an unnamed person.',
    'Speaks in a constant whisper.',
    'Refers to themselves in the third person.',
    'Always hungry; eats during conversations.',
    'Carries a small, fidget-worthy talisman.',
    'Suspicious of anyone in good shoes.',
    'Has a beloved pet they mention often.',
    'Avoids saying their own name aloud.',
    'Constantly checks the position of the sun or moon.',
    'Always pays in copper, even for large purchases.',
    'Sneezes when telling a lie.',
    'Hates being touched on the shoulder.',
    'Counts coins three times before pocketing them.',
    'Wears too many rings; jingles when walking.',
    'Speaks with a foreign accent that slips when angry.',
    'Quotes a long-dead philosopher in every conversation.',
    'Insists doors should always be closed behind people.',
    'Carries a notebook full of unfinished poems.',
    'Knows the name of every dog in town.',
    'Suspects every shadow contains an agent of an old enemy.',
    'Smells faintly of a strong, unidentifiable spice.',
    'Has one milk-white eye that twitches when nervous.',
    'Begins every sentence with "Now, listen here…"',
    'Sings under their breath while working.',
    'Refuses to enter a building without first asking permission.',
    'Cracks knuckles after every controversial statement.',
    'Owes money to a dangerous person and avoids the topic.',
    'Believes themselves the rightful heir of a forgotten title.',
    'Names every weapon they own.',
    'Talks to a hand-puppet they keep in their belt.',
    'Insists on shaking hands twice before any deal.',
    'Lost a sibling and mistakes strangers for them.',
    'Refuses to make eye contact with anyone in armor.',
    'Has a perfect memory for prices but forgets faces.',
    'Fingers a holy symbol whenever startled.',
    'Grew up at sea and finds inland weather unsettling.',
    'Loves riddles, hates straight answers.',
    'Once survived a wolf attack and never wears wool.',
    'Calls everyone, regardless of age, "kid".',
    'Carries a flask of something they never offer to share.',
    'Eats only food they cooked themselves.',
    'Reads the bones of animals to plan their day.',
    'Refuses to step on shadows during the day.',
    'Always sits with their back to a wall.',
    'Has been thrown out of three taverns this month.',
    'Wears a coat several sizes too large, "in case I grow into it".',
    'Believes they are being followed by a kindly ghost.',
    'Translates aloud what their dog or horse "is thinking".',
    'Whispers to plants in the marketplace.',
    'Loves bad puns and rates them out of ten.',
    'Will not light a fire on the first night of a journey.',
  ),

  pack(
    'NPC name (fantasy)',
    'A general-purpose first-name pool — mix of cultures and tones.',
    'Aila', 'Bram', 'Cael', 'Doryn', 'Eira', 'Faelan', 'Greta', 'Hesta',
    'Ilya', 'Jorin', 'Kael', 'Loren', 'Mira', 'Nessa', 'Orin', 'Petra',
    'Quill', 'Rolan', 'Sera', 'Tomas', 'Una', 'Vael', 'Wren', 'Yara',
    'Zorin', 'Aldric', 'Brena', 'Corwin', 'Dara', 'Elias',
    'Ferren', 'Galwen', 'Hrothgar', 'Inara', 'Jevan', 'Korrin', 'Lythra',
    'Marek', 'Nyx', 'Olen', 'Perrin', 'Quentin', 'Ranek', 'Sable',
    'Theron', 'Ulric', 'Veska', 'Wilder', 'Xanthe', 'Ylva',
  ),

  pack(
    'NPC profession',
    'A trade or station to anchor an unnamed person.',
    'Apothecary', 'Astrologer', 'Baker', 'Beekeeper', 'Beggar',
    'Blacksmith', 'Bookbinder', 'Brewer', 'Butcher', 'Candlemaker',
    'Caravan guard', 'Cartographer', 'Cobbler', 'Cook', 'Cooper',
    'Courier', 'Farmer', 'Farrier', 'Fishmonger', 'Fletcher',
    'Glassblower', 'Groom', 'Guildsman', 'Hedge witch', 'Herbalist',
    'Hunter', 'Innkeeper', 'Jeweler', 'Lamplighter', 'Locksmith',
    'Mason', 'Midwife', 'Miller', 'Minstrel', 'Net-mender',
    'Notary', 'Pickpocket', 'Priest', 'Ratcatcher', 'Sage',
    'Sailor', 'Scribe', 'Shepherd', 'Stonecutter', 'Tanner',
    'Tax collector', 'Tinker', 'Wainwright', 'Watchman', 'Weaver',
  ),

  pack(
    'NPC appearance',
    'A distinguishing feature so they are remembered.',
    'A pale scar from forehead to chin.',
    'Eyes of two different colors.',
    'A milky-white left eye.',
    'Three fingers on the off hand.',
    'A perpetually crooked smile.',
    'Heavy bags under the eyes.',
    'Hair shaved on one side.',
    'A neck tattoo half-hidden by a collar.',
    'A missing front tooth.',
    'A tongue too quick for the face.',
    'Scars on the knuckles.',
    'A nervous tic in the left eye.',
    'A faint scent of lavender.',
    'Calluses from a craft long abandoned.',
    'A limp on the right side.',
    'Hands stained with old ink.',
    "A laugh that doesn't reach the eyes.",
    'An ear lobe with three rings.',
    'A faint birthmark on the cheek.',
    'Posture too straight for a peasant.',
    'A jagged front tooth from an old fight.',
    'Hair white at the temples but black elsewhere.',
    'A faint stutter that disappears when angry.',
    "Eyebrows that won't stay neat.",
    'Cheeks that flush at the slightest emotion.',
    'A voice rougher than expected for the face.',
    'A faint tremor in the offhand.',
    'A burn scar shaped like a half-moon.',
    'Always carrying the smell of woodsmoke.',
    'A noticeably slow blink.',
    'A small notebook tucked behind one ear.',
    'A ribbon braided into a single lock of hair.',
    'Boots polished to a mirror shine despite mud everywhere.',
    'A faint accent that shifts mid-sentence.',
    'Fingers stained green from herbs.',
    'A stoop suggesting old labor.',
    'A locket worn outside the shirt.',
    'One ear higher than the other.',
    'A faint, persistent cough.',
    'Bright clean teeth in a weathered face.',
    'A wrist marked by old rope-burns.',
    'A patch of skin that flushes red unevenly.',
    'Hands always cold, no matter the weather.',
    'A mole at the corner of the mouth that moves when they smile.',
    'Hair tied back with a strip of leather.',
    'A faint scent of smoked meat.',
    'An old earring hole, no earring.',
    'A nose broken twice and set differently each time.',
    'Always glancing toward the door.',
    'A small carved bead on a thong around the neck.',
  ),

  pack(
    'Tavern name',
    'A place to drink, rest, or be overheard.',
    'The Crooked Goat', 'The Sleeping Dragon', 'Three Oaks',
    'The Last Lantern', "Mother Bess's", 'The Salty Crow',
    'The Wayfarer', 'Hood and Hatchet', 'The Brass Anchor',
    'The Painted Door', 'Old Hen and Hammer', 'The Quiet Mug',
    'The Drunken Friar', 'The Burnt Loaf', 'The Silver Stag',
    'The Drowned Rat', 'The Cracked Bell', 'The Iron Knot',
    "The Pilgrim's Cup", 'The Singing Stone', 'The Foxhound',
    'The Last Coin', 'The Tilting Tankard', 'The Cold Hearth',
    'The Black Boar', 'The Wandering Cup', 'The Hare and Hound',
    'The Knot of Crows', 'The Three Sisters', 'The Cracked Tooth',
    'The Inkwell', 'The Cobblestone', 'The Rusty Anchor',
    "The Pilgrim's Foot", 'The Old Mill', 'The Whistling Kettle',
    'The Long Mile', 'The Drowned Lamp', "The Beggar's Bargain",
    'The Greenwood Door', 'The Iron Hen', 'The Singing Hammer',
    'The Two Brothers', 'The Stoic Toad', 'The Penny Loaf',
    'The Hollow Tree', 'The Smiling Spider', 'The Last Bridge',
    'The Halfway Inn', 'The Bone and Beer',
  ),

  pack(
    'Tavern patron',
    "Who's at the bar tonight?",
    'A merchant nursing wine and reading a folded letter.',
    'A pair of soldiers — one drunk, one wary.',
    'A hooded figure who flinches when the door opens.',
    'A bard tuning a stringed instrument too slowly.',
    "Three apprentices arguing about a master's debt.",
    "An old woman who hasn't said a word in an hour.",
    'A traveler tracing a map on the table with a finger.',
    'A young noble pretending not to be one.',
    'Twin brothers playing dice for stupid stakes.',
    'A hunter with a fresh wound and a story.',
    'A scribe sketching the regulars.',
    "A retired adventurer who's told this tale before.",
    'A priest of an obscure local saint.',
    'A cook taking a rare break, smelling of onions.',
    'A drunk singing the wrong words to a familiar song.',
    'A smuggler arguing prices in low tones with the keeper.',
    "A tanner whose hands won't come clean.",
    'A messenger asleep over half a meal.',
    'A farmer talking too loud about his prize sow.',
    'A widow drinking measured cups in silence.',
    'A pair of locals arguing about boundaries on a fence.',
    'A young couple deliberately not looking at each other.',
    'A bard counting the take from a hat.',
    'A traveler with three coats too many for the weather.',
    'A blind old man whose dog watches the room.',
    "A noble's third son hiding from a tutor.",
    'A mason settling a dispute about pay.',
    'A peddler counting the same coins again.',
    'A pilgrim sharing food with a stranger.',
    'A retired guard recognizing too many faces.',
    'A foreign sailor practicing the local dialect.',
    'A herbalist haggling with the cook for a herb.',
    'A scribe being paid in coin for letters home.',
    'A musician trying to sell a song to a drunk.',
    'A nun off-duty, drinking surprisingly well.',
    "A boy passed off as fifteen, who isn't.",
    'A weaver napping with a pint untouched.',
    'A surveyor with rolled maps under his arm.',
    'A reeve writing names down, slowly.',
    'A miner with too-clean hands today.',
    "A merchant's apprentice carrying a bird in a cage.",
    'A retired soldier teaching dice to a child.',
    'A priestess noting the regulars in a small book.',
    'A drover stinking of cattle and pleased with the price.',
    'A young woman dressed as a man, badly.',
    'A judge of small disputes between cups.',
    'A sellsword sober, watching the room.',
    "A boatman counting the stories he'll tell tomorrow.",
    "A merchant whose wagon stands outside, wrong wheels.",
    'A woman at the bar who came in twice and never left.',
  ),

  pack(
    'Rumour',
    'Something overheard or whispered.',
    "The miller's youngest hasn't been seen in three days.",
    'Lights have been moving on the old hill at night.',
    'A stranger paid the inn in foreign coin.',
    'The trail through the wood is washed out, but a path no one remembers is open instead.',
    "The reeve's son's hand is bandaged and he's saying nothing.",
    'A wolf has been seen too close to the village, and not behaving like a wolf.',
    'The shrine on the hill has new offerings, but no one will say from whom.',
    'A peddler is selling charms that he claims work.',
    'The high road is closed but the toll-collector is still there.',
    'Cattle have stopped grazing the south meadow.',
    'A child described, in detail, a person no one knows.',
    'The river ran black for an hour at dawn.',
    'Old debts are being collected by someone new.',
    'A rider came at midnight, asked for the priest, left at dawn.',
    "There's a coin minted in a kingdom that hasn't existed for years.",
    "The cooper's apprentice has been talking in his sleep — and not in his own voice.",
    'A grave was disturbed, but the body remains.',
    'A wedding has been postponed, twice, and no one will say why.',
    "The baker's bread tastes faintly of iron this week.",
    "Crows are gathering on the old mill, even when there's nothing to gather for.",
    'Someone has been leaving fresh bread on the steps of the abandoned house.',
    "A traveling player walked into the woods two nights ago and hasn't been seen since.",
    "The reeve's daughter cries in her sleep and won't say why.",
    'A song no one wrote is being whistled by half the town.',
    'Three children claim to have seen the same stranger, on three different roads, on the same night.',
    'The price of salt has tripled, but no merchant will explain why.',
    "A bell that hasn't rung in twenty years rang once last week.",
    'A lamb was born with markings nobody likes.',
    "The blacksmith's hammer broke on a sword he'd been told not to forge.",
    "Someone burned a letter in the inn's hearth, and the ashes wouldn't go cold.",
    'A widow swears her husband walked past the window at dusk.',
    'Footprints lead from the riverbank to the church door, then stop.',
    "The miller's grain bins are emptier than they should be, but no rats.",
    'A stranger paid double for a single mug of ale and asked nothing in return.',
    'The barber heard names whispered through the wall last night.',
    'A goat was found alive but somehow on the wrong side of a locked barn.',
    'The watchman swears the main bell tolled once, but no one rang it.',
    'A dog from another village will not stop following the priest.',
    "The lord's son has been seen at the wrong inns, with the wrong company.",
    'Someone left flowers on the grave of a man who was never buried.',
    'A horse came back from the road without its rider, and no one is missing.',
    "The cobbler has refused all custom for a week and won't say why.",
    'The fishmonger keeps a basket she will let no one near.',
    'A trader passed through, sold nothing, asked questions, and left.',
    'Smoke rises from the abandoned tower at moonrise.',
    'A scholar arrived asking about a name no one will repeat.',
    'The well water tastes wrong on Tuesdays.',
    "A child's drawing on the church wall keeps reappearing after it's washed off.",
    "The candle the priest lit for the dead won't go out.",
    'Three barns burned in a row, on three different farms, in three days.',
  ),

  pack(
    'Plot hook',
    'A seed for the next session.',
    'A box arrives addressed to no one, locked, and humming faintly.',
    "A child says they've seen the same dream three nights running, and so has another child.",
    'A merchant offers an absurd reward for the safe escort of an ordinary-looking crate.',
    "A friend's letter ends mid-sentence.",
    'A bell tolls in a church no one remembers being there yesterday.',
    'The price of bread has tripled overnight in the next town.',
    'A friendly NPC asks the party to deliver a message they cannot read.',
    "A coin from the party's last reward turns out to be cursed.",
    'A familiar face on a wanted poster — but the name is wrong.',
    'The lord summons the party for a private audience and arrives wounded.',
    "A map is drawn into the dust at the inn's door each morning, fading by noon.",
    'An old enemy sends a gift.',
    'The party wakes covered in soot and cannot remember the night.',
    'The well in the village square reflects the wrong sky.',
    'A child the party has never met calls one of them by name.',
    'A scribe is hired to forge a will the party would benefit from.',
    "A chest the party owns has acquired a second lock they didn't put there.",
    "A messenger insists they've delivered the letter the party hasn't yet written.",
    "A merchant pays the party in advance for a job they haven't agreed to.",
    "The road they took yesterday isn't where they remember it being.",
    "A stray dog won't leave the party, but turns away from one specific member.",
    'A drunk in a tavern hails the party as if they had met before — and remembers things they should not know.',
    "The party's horses refuse to enter a particular village.",
    'A stranger collapses in front of the party with a token of theirs in hand.',
    'A bounty notice goes up for a person no one has ever seen.',
    'A captured prisoner asks to speak to one party member alone, then refuses to say why.',
    "The party's quartermaster receipts don't match the gear they have.",
    'A locked door in their lodgings is open in the morning.',
    'A friendly innkeeper has been replaced by someone who knows the same details.',
    'A figure has been seen following the party at exactly twelve paces back.',
    'A hawk circles overhead at every camp for a week.',
    "A childhood toy of a party member shows up in a foreign market.",
    "A scholar offers to pay for a memory the party can't recall having.",
    "The body of a stranger washes ashore wearing the party's colors.",
    "A party member's reflection lags by half a second in still water.",
    'The local priest asks the party to attend a funeral for someone still alive.',
    'A village they have never visited has built a small monument to one of them.',
    'A merchant offers gold to NOT deliver a message.',
    'A noble offers gold to forget seeing them at all.',
    'A traveling troupe asks the party to play themselves in a play.',
    'A storm follows the party, and only the party.',
    "The mayor's chains of office have been replaced; the mayor doesn't seem to notice.",
    'A tax collector arrives with a writ no one in town can read.',
    'A rumour reaches the party of a tomb opened, then sealed again, by the same expedition.',
    'A stranger leaves the party a key and says only "for when".',
    'A seller at a market has the party\'s stolen items but did not steal them.',
    'A child claims they have been "promised" to the party.',
    'The lord declares a feast in honor of guests the party has never heard of.',
    "A relic the party doesn't own is stolen from them.",
    'Their last meal still tastes of the wrong herbs.',
  ),

  pack(
    'Wilderness encounter',
    'A meeting on the road, in the woods, or off the trail.',
    'A pack of wild dogs, hungry and bold.',
    'A merchant cart, axle broken, owner panicked.',
    'A hooded rider going the other way, who never looks up.',
    'A copse where every tree has been bled to mark a path.',
    'A child, alone and unhurt, refusing to speak.',
    'Smoke on the wind from no fire you can see.',
    'A clearing where the grass has been pressed flat in a circle.',
    "A wounded animal that doesn't run from you.",
    'A stone with new markings on it.',
    'A hunter who claims the woods are wrong today.',
    'A traveler with a story too good for these parts.',
    'A shrine, freshly tended, far from any town.',
    'Birds wheeling over a single point a mile off.',
    'Footprints that go forward and stop.',
    'A stretch of road where the air feels thick.',
    'A messenger riding too hard for safety.',
    'A bear, calm, with old armor strapped to its back.',
    'Three identical travellers walking in single file.',
    'A fresh grave with no marker.',
    'An overturned wagon, contents untouched.',
    "A circle of mushrooms that wasn't there yesterday.",
    'A pilgrim leaving offerings on each milestone.',
    "A trapper checking snares that aren't his own.",
    'A mounted noble with no entourage and a broken sword.',
    'A dog dragging a leash, no master in sight.',
    'A traveler asking to share fire — for too long, in silence.',
    'A stretch of road where every birdcall sounds wrong.',
    'A scribe sitting in a clearing, writing furiously.',
    'A masked rider, polite, who refuses to give a name.',
    'A peddler whose wares match exactly what the party needs.',
    "A fight in progress between strangers who fall silent at the party's approach.",
    'A small chapel by the road, doors open, no one home.',
    'A line of horses tied to a tree, with no riders.',
    'A fox carrying something man-made.',
    "A field of crows that doesn't startle when you pass.",
    'A merchant haggling alone at the side of the road.',
    'A spring boiling over without heat.',
    'A man asleep across the path, breathing slow.',
    "A child's shoe on a stone, no other tracks.",
    'A stretch where every leaf has been pulled inside-out.',
    'A column of smoke that does not move with the wind.',
    'A traveler whose horse refuses to step where their feet step.',
    'A flock of sheep without a shepherd, calm.',
    'A messenger who falls dead at your feet without a wound.',
    "A soldier hiding in a bush, watching a road that isn't there.",
    'A patch of forest where the trees are all the wrong species.',
    "A rider whose face you've seen before but cannot place.",
    'A wagon driver convinced he passed you on the road three hours ago.',
    "A stretch of river where your reflection isn't quite right.",
    "A signpost pointing to a village that doesn't exist.",
  ),

  pack(
    'Urban encounter',
    "Something happens on the city's streets.",
    'A pickpocket bumps into the party and apologizes too much.',
    "A street performer's audience scatters mid-song.",
    'A dog refuses to enter a particular shop.',
    'Two guards argue in a side street about who saw what.',
    'A child hands the party a folded note, then runs.',
    "A wagon spills its contents — what was inside isn't what was claimed.",
    "A duel has just ended; the winner is calm, the watch isn't.",
    "Funeral procession of someone the city doesn't agree was important.",
    "Someone is selling something cheap that obviously isn't theirs.",
    'A street preacher names the party in his sermon.',
    'Beggars cluster around a doorway no one will enter.',
    'A horse collapses and people argue about whose it is.',
    'A merchant runs after a customer for the wrong reason.',
    "A patrol stops the party to ask about someone matching their description.",
    'Two children play a game that involves a chant in a dead language.',
    'A door opens of its own accord, briefly, then closes.',
    'A scribe is surrounded by a crowd, reading a public letter aloud.',
    'A herald calls names, none of them anyone present.',
    'A sleeping drunk has a sealed letter pinned to their coat.',
    "A stallholder is selling fruit from a basket that wasn't there an hour ago.",
    "A noble's coach passes too close, and a child is jostled — the coach stops.",
    'A pickpocket runs the wrong way, into the watch.',
    "A street fight ends when one combatant says the other's true name.",
    'A street preacher refuses payment to be quiet.',
    'A merchant invites the party to dinner; nothing about him fits.',
    'A man in fine clothes is begging — quietly, expertly.',
    "A kitchen boy throws away food that's clearly fresh, with reverence.",
    "A bell tower's bird tower is empty for the first time anyone remembers.",
    'A drunkard reels but never spills the cup.',
    'A boy is being chased — the chasers shout the wrong name.',
    'A guard is scrubbing a doorway clean of something dark.',
    'A funeral parlor has a queue.',
    'A scribe is paid to NOT write.',
    'A messenger waits patiently at a door no one ever uses.',
    'A dog in livery moves through the crowd as if on errand.',
    'A hooded figure leaves a coin where one wasn\'t.',
    'A man yells the same word three times, then walks away.',
    'A bookseller refuses to sell a book to a noble.',
    'A juggler keeps an extra ball aloft when only three should be up.',
    'A child trades a copper for a kindness, formally, with a bow.',
    'A market clears at the toll of an unscheduled bell.',
    'A merchant stops the party and asks if they can be trusted.',
    "A patrol salutes someone in the crowd; the person doesn't look up.",
    'A door is open that should be shut, with a chair in front of it from the inside.',
    'A drunk recites a poem in a language no one knows.',
    'A young woman drops a glove deliberately, watches the party.',
    'A beggar has the same coat as a noble passing by.',
    'A horse without a rider walks a deliberate route through the streets.',
    'A man with a cage of crickets sells silence by the minute.',
    'Someone is paying very small children to keep watch on something.',
  ),

  pack(
    'Mundane loot',
    'What you find in a pocket, a pouch, a drawer.',
    'A handful of polished river stones.',
    'Three dice carved from bone.',
    'A cracked pewter spoon.',
    'A sealed bottle, contents unknown.',
    'A small brass bell on a leather thong.',
    'A single fine silver button.',
    "A child's drawing of a stranger.",
    'A coil of strong, thin wire.',
    'A bundle of dried herbs, unlabeled.',
    'A chipped ceramic cup with a faded crest.',
    'A wax seal stamp of an unfamiliar sigil.',
    'A half-eaten loaf of dark bread.',
    "A wooden whistle that doesn't make a sound.",
    'A ring of keys, none fitting any lock you know.',
    'A bone needle and gut thread.',
    'A folded scrap of vellum with a list of names crossed out.',
    "A tarnished tin lover's locket, empty inside.",
    'A leather strap with notches counting something.',
    'A wooden comb, half its teeth gone.',
    'A pouch of mismatched buttons.',
    'A sliver of a broken mirror, kept carefully.',
    'A piece of charcoal from a long-dead campfire.',
    'A loop of hair, color changing in the light.',
    'A pewter ring worn thin on the inside.',
    "A boy's tooth, kept in folded cloth.",
    'A coin from a foreign land, value unknown.',
    'A scrap of map, edges burned.',
    'A length of rope braided in three colors.',
    'A small wooden box with three compartments, one empty.',
    'A sprig of dried thyme tied with a red string.',
    "A bird's feather, white where it should be black.",
    'A half-finished carving of an animal, unidentifiable.',
    'A pebble inscribed with a single rune.',
    'A bag of marbles, each a different size.',
    'A shaving razor in a tin case.',
    'A folded parchment showing teeth marks at one corner.',
    'A signet ring with the seal worn smooth.',
    'A small clay flask, sealed with wax, light when shaken.',
    'A leather wallet with three foreign coins inside.',
    'A piece of polished antler.',
    "A child's wooden horse, missing a leg.",
    'A length of black ribbon, faintly perfumed.',
    'A clay tile painted with a single eye.',
    'A small leather-bound book, blank pages, well-worn.',
    'A dried flower pressed flat, color preserved.',
    'A pin shaped like a fish.',
    'A pouch of teeth — animal, mostly.',
    'A small candle stub still warm.',
    'A folded handkerchief embroidered with a name nobody knows.',
    'A cracked stone whistle that summons something inadequate.',
  ),

  pack(
    'Magic-item spark',
    'The small twist that makes an item interesting.',
    "The wielder briefly hears their own thoughts in another voice.",
    'Once per day, the holder dreams a true thing about a stranger.',
    'In firelight the metal looks like another metal entirely.',
    "Animals will not approach within an arm's length of it.",
    'Snow does not stick to the bearer.',
    'Coins balanced on it never fall.',
    'The bearer can always tell true north.',
    "Plants nearby grow, slightly, when it's drawn.",
    'It hums faintly when a lie is spoken in its presence.',
    'It feels warm to the bearer even in winter.',
    'Once a month, it weighs nothing for an hour.',
    'It has a name no one taught you.',
    'Birds that see it follow for a while.',
    'Its shadow lags by half a heartbeat.',
    'Dust does not settle on it.',
    "The bearer's footsteps make no sound on grass.",
    'Fire near it burns blue at the tips.',
    'It cannot be stolen while the bearer is asleep.',
    'Water touched to it never freezes.',
    'The bearer always wakes at the same hour.',
    'Salt poured on it draws into a circle.',
    'Songs sung in its presence are remembered exactly.',
    'Knots tied around it never tighten.',
    'The bearer cannot be lost in a familiar town.',
    'Bees ignore the bearer, even angered ones.',
    "The bearer's name is harder to remember; their face is not.",
    'Cuts made by it bleed cleanly and heal one night faster.',
    'Once a week, it is briefly, faintly, the wrong color.',
    'The bearer always steps over thresholds with the right foot first.',
    'Wax sealing it keeps soft for an hour.',
    "The bearer's reflection blinks before they do.",
    'Iron filings near it stand up.',
    'It sings, very softly, when the bearer is being watched.',
    "The bearer's heart can be heard, very faintly, from arm's length.",
    'Wine poured into a cup it has touched tastes like the place it was made.',
    'Children are drawn to it, then suddenly bored.',
    "Maps in the bearer's hand show one extra detail others' don't.",
    'Snowflakes near it pause for a heartbeat before falling.',
    'The bearer does not get drunk on the first cup of any wine.',
    'Locks the bearer touches stick once, then turn smoothly.',
    'Bread baked while it sits on the windowsill keeps three days longer.',
    'Doors close behind the bearer with no help.',
    "The bearer's tears are slightly luminous in dark rooms.",
    'Cards drawn from a deck the bearer touched fall in face order.',
    "Weather changes a notch in the bearer's favor at noon.",
    'Knives sheathed with it stay sharp longer.',
    'The bearer is never quite where they are expected to be.',
    'Candles near it burn taller, not faster.',
    "The bearer hums a tune they don't know.",
    'Ink dries instantly on writing about it.',
  ),

  pack(
    'Weather today',
    'What the sky is doing.',
    'Clear and cold; breath visible.',
    'Overcast with low, heavy clouds.',
    'Steady, fine drizzle.',
    'Bright sun and a sharp wind.',
    'Fog so thick the next building is rumour.',
    'A morning of rain, an afternoon of sun.',
    'Cloudless and hot; the road shimmers.',
    'Sleet, sharp enough to sting.',
    'Heavy snow, falling straight down.',
    'Wind out of an unusual quarter.',
    'Threatening sky that never breaks.',
    'A still grey day — no wind, no birds.',
    "Light snow that doesn't settle.",
    'Hail for ten minutes, then nothing.',
    'Warm and humid; everything sticks.',
    'Strange amber light, like dusk at midday.',
    'Rain so fine it floats sideways.',
    'Cold air that bites and goes.',
    'Wind strong enough to lean into.',
    'Mist rising from the river by midmorning.',
    'Sun behind a thin haze; warm but not bright.',
    'A heat that breaks at evening with thunder.',
    'Snow falling, then stopping, then falling again.',
    'A clear sky with one strange, lingering cloud.',
    'Wind that drops dead at noon.',
    'A morning of frost, gone by midday.',
    'Drizzle that stops and starts every quarter hour.',
    'Air thick with the smell of the sea, miles inland.',
    'A red sun rising too slowly.',
    'Snow with a faint smell of smoke.',
    'A grey sky and unusually bright shadows.',
    'Sudden rain on a cloudless day.',
    'Cold with a strange warm breeze.',
    'A storm visible in the distance, going elsewhere.',
    'A still, hot afternoon broken by a cool draft.',
    'Frost on the north sides of trees only.',
    'Rain that never quite arrives.',
    'A wind that smells of wet stone.',
    'Bright cold sun reflecting hard off snow.',
    'A sky busy with crows.',
    'Moonlit night so bright you cast a shadow.',
    'A morning where the dew is heavier than expected.',
    'A breeze that carries voices from far off.',
    'Clouds moving the wrong way.',
    'A storm that arrives and leaves in twenty minutes.',
    'A night still warm from the day.',
    'Light fog that smells of woodsmoke.',
    'A high, thin wind audible only inside.',
    'A day where your shadow seems shorter than it should.',
    'Sky overcast in the morning, clear at dusk, with stars before they should be visible.',
  ),

  pack(
    'Distant sound',
    'The noise that breaks the silence.',
    'A bell, tolling once, far off.',
    'The clatter of something metal falling, thrice.',
    'A long, drawn-out note from no instrument you know.',
    "Children laughing where there shouldn't be children.",
    'A horse, distressed, then silent.',
    'A door slamming, again, the same door.',
    'Wood splitting under weight.',
    "A song with words you can almost catch.",
    'Something heavy being dragged.',
    'A whistle, three sharp notes.',
    'Wings, large, moving fast.',
    'Many small footsteps, not running.',
    'A blade being drawn, then sheathed.',
    "A laugh that isn't quite a laugh.",
    "A chant, low, in a tongue you don't know.",
    'A wagon wheel breaking against stone.',
    'A baby crying, briefly.',
    'The rasp of a saw, far enough to be uncertain.',
    'Someone hammering a nail, paused, hammering again.',
    'A whisper close to your ear, with no one beside you.',
    'A bell rung only once, badly.',
    'A name you know, called from too far to be sure.',
    "A door that won't quite close.",
    "A horse's hooves, not running, not walking.",
    'A coin dropped on stone.',
    'The creak of wood under a slow weight.',
    "A fox's cry that lingers too long.",
    'The grind of millstones, late at night.',
    'A choir, briefly, then nothing.',
    'A glass shattering somewhere in a still house.',
    'The wet thud of something falling far off.',
    'A boot scraping a doorstep.',
    'A prayer, half-heard, ending.',
    'A page turning beside you when you are alone.',
    'The clack of dice on wood.',
    'A horse blowing softly outside the window.',
    'The hiss of a kettle, with no kettle.',
    'A child counting to ten very deliberately.',
    'The crack of ice on a hot day.',
    'The drag of a chain across stone.',
    'A pot lid falling and rolling slowly to a stop.',
    'The sound of a needle being pulled through cloth.',
    'The scrape of chair legs on the floor above.',
    'The flap of a heavy book opened.',
    'A drum, deep, heard through water.',
    'A creature breathing where there is nothing alive.',
    'The click of a lock turning in an empty room.',
    'A long sigh from a window across the street.',
    'Pebbles falling down a flight of stone steps.',
    'A whistle, one note, in tune with whatever you were thinking.',
  ),

  pack(
    'Strange smell',
    "What your nose catches that shouldn't be there.",
    'Something sweet, just on the edge of cloying.',
    'Wet stone and old rust.',
    "Smoke that doesn't smell of any wood you know.",
    'A scent of cooking from an empty kitchen.',
    'Fresh bread where there is no bakery.',
    'A perfume someone you used to know wore.',
    'The clean cold smell of deep water.',
    'Dry leaves underfoot in the wrong season.',
    'Lamp oil, faint, with a metallic edge.',
    'Animal musk, but not from any animal you can name.',
    'Brine, far from any sea.',
    'The aftermath of a fire long since extinguished.',
    'Lily, faint, sickly.',
    'Hot iron from a forge, with no forge in sight.',
    'Apples baking in winter.',
    'Wet wool on a dry day.',
    'Pine sap, in a place with no pines.',
    "A child's hair, freshly washed.",
    'The dry electric smell of approaching lightning.',
    'Vinegar, sharp, then gone.',
    'Old paper turning to dust.',
    'The smell of a stable, swept clean.',
    'A kitchen the morning after a feast.',
    'Wet ash and warm bread.',
    "A pond's bottom in the heat of summer.",
    'The clean cold smell of a chapel after candles.',
    "Something burning that shouldn't burn.",
    'The starchy smell of porridge made too long ago.',
    'The breath of a horse, gentle.',
    'The smell of a sick room aired out too late.',
    'Wet hemp rope.',
    'The dry smell of grain in a closed loft.',
    "Camphor, like an old drawer's lining.",
    'The smell of lye soap, recently used.',
    'The mineral smell of cold water from a stone spring.',
    'The faint warmth of beeswax.',
    'The musk of old vellum.',
    'Hot tin, like the inside of a kettle.',
    'The smell of leaves crushed in a hand.',
    'Goose fat, rendered hours ago.',
    'Dust sliding off old velvet.',
    'Cold metal, like a coin in winter.',
    'Cinders quenched in milk.',
    'Salt drying on rope.',
    'A walnut, cracked in a dry hand.',
    'Linen pressed with rosemary.',
    'The thin sweet smell of decay just beginning.',
    'A pipe smoked some days ago.',
    'The shed of a cat lying in sun.',
    'The way a forge smells after the last fire of the season.',
  ),

  pack(
    'Critical hit flair',
    'Description for a clean blow.',
    'A clean, decisive blow — the kind bards exaggerate later.',
    'Knocks the target back a full pace.',
    "Splits the haft of an enemy's weapon.",
    'Sends a helmet rolling.',
    'Draws a long line of bright blood across cloth.',
    'Lifts the target from their feet for an instant.',
    'Lodges, briefly; you have to twist it free.',
    'Shears straps and laces in a way that exposes more than the wound.',
    'A glancing blow that nonetheless strikes a nerve — they go briefly numb.',
    'The stroke smashes the buckle of a belt; pouches fall.',
    'Strikes near the eye; vision in that eye is impaired.',
    'Ribs crack audibly.',
    "Disarms; their weapon spins through the air.",
    'The crack of the strike echoes off nearby walls.',
    'The strike sets sparks at the metal.',
    'The blow drives the target back into a wall.',
    "A clean cut to the brow blinds the target with their own blood.",
    'The strike shears a strap; armor sags.',
    "The blow turns the target's footing; they stumble.",
    'The hit catches a buckle; the breastplate lurches.',
    'The strike pries loose a tooth.',
    "The hit lands flush; the target's breath is knocked out.",
    'The blow crosses an old scar; the target reacts.',
    'The strike unstrings a bow.',
    'The hit pierces deep; the target sets their jaw.',
    'The blow lands solidly enough to ring the helmet.',
    'The strike severs a hair-tie; long hair falls into eyes.',
    'The hit cracks the boss of a shield, splintering inward.',
    'The blow lifts the target half a step.',
    'The strike stuns; the target hears nothing for a beat.',
    'The hit catches a sleeve; cloth tears away.',
    'The blow snaps a bowstring close to the hand.',
    'The strike marks a vein clearly; bleeding is visible.',
    'The hit cracks a vambrace; the bracer hangs loose.',
    'The blow catches the target stepping in; they fall to a knee.',
    'The strike disarms; their weapon clatters several paces away.',
    "The hit drives the target's foot off-balance into a puddle.",
    'The blow whistles before it lands.',
    "The strike lands a clean line down the target's brow to the chin.",
    'The hit knocks loose a pouch; coins spill.',
    'The blow leaves a bruise visible already.',
    'The strike rips a banner from a haft.',
    "The hit echoes through the target's chest plate.",
    "The blow sets the target's helm askew; they cannot see for a beat.",
    'The strike severs a chinstrap; their helm falls.',
    'The hit lands so well the watching allies cheer.',
    "The blow cuts the target's belt; their scabbard drops.",
    'The strike sets the air ringing.',
    'The hit lands on an old wound that opens fresh.',
    'The blow drives the breath out and the target falters for the next round.',
  ),

  pack(
    'Mishap on a long rest',
    'What went a little wrong overnight.',
    'Boots are wet through; takes an hour to dry them.',
    "Someone's cloak was torn by a careless branch.",
    'A pack of dried meat went off in the night.',
    'A small thief took something — a coin, a needle, a button.',
    'The watch missed an hour, and there are unfamiliar tracks just beyond camp.',
    'A horse came up lame in the night.',
    "A dream so vivid one of you can't shake it.",
    'Rain found the gear despite the cover.',
    'A spell focus has hairline cracks none of you can explain.',
    'The fire died early; everyone is colder than they should be.',
    'A flask of water tastes faintly of iron in the morning.',
    "One of you woke with a feeling that shouldn't be there yet.",
    'A bowstring snapped without being touched.',
    'A page is missing from a book you keep close.',
    "The fire wouldn't catch for an hour, no reason given.",
    'A boot strap is severed clean, as if cut.',
    'The dawn smells of smoke from a fire none of you lit.',
    'A small bird has died in the camp, untouched.',
    "A horse has been brushed in the night; you know it wasn't you.",
    "The cookfire's coals are scattered in a pattern.",
    'A blanket is missing — none of you remember a wind.',
    'The water in the kettle is cold enough to hurt your teeth.',
    "A coin you've never seen sits on top of your pack.",
    'Someone has retied your tent ropes, and better than you would.',
    'A note in handwriting you almost recognize sits inside your boot.',
    'Your knife is back in its sheath, but the blade is wet.',
    'A pot of porridge is half-eaten and warm.',
    "A dog you've never seen is asleep in the camp.",
    'A guttered candle still gives off thin smoke.',
    'A small feather is tucked into the fold of one of your maps.',
    "Someone's bowstring is wound the wrong way.",
    'The horses are facing east, all of them.',
    "A song no one sang is in everyone's head.",
    'A name written in the ash of the fire, unfamiliar.',
    'A boot has new mud on it, when no one has walked.',
    "The cookfire's stones have been moved a step.",
    "A child's footprint near the watering spot.",
    'A new patch sewn neatly into the side of a bag.',
    'A pebble carved with a single line on the inside of your bedroll.',
    'A torch you snuffed is warm to the touch.',
    'A small bouquet of weeds at the head of your bedroll.',
    'The stars above the camp are wrong by half a hand.',
    "A page in the spellbook is damp, but it didn't rain.",
    'The morning is too quiet — no birds, no insects.',
    'A cup of water has frozen on a warm night.',
    'A low whistle answers from the trees when you whistle in camp.',
    'The ration tin, sealed last night, is now empty.',
    'A trail of footprints comes to your bedroll and stops.',
    "The horses are calm in a way they haven't been in days.",
    'One of your spells feels different, just slightly, when prepared.',
  ),
]

export function newEntry(overrides = {}) {
  return {
    id: uuid(),
    text: overrides.text ?? '',
    weight: clampWeight(overrides.weight ?? 1),
  }
}

export function newTable(overrides = {}) {
  return {
    id: uuid(),
    name: overrides.name ?? 'New table',
    description: overrides.description ?? '',
    entries: overrides.entries
      ? overrides.entries.map(newEntry)
      : [newEntry({ text: '' })],
  }
}

function clampWeight(w) {
  const n = Number(w)
  if (!isFinite(n) || n < 0) return 1
  return Math.min(1000, Math.max(0, n))
}

// New libraries seed with the full starter pack so first-time users
// have ~850 entries across 17 tables ready to roll.
export function emptyLibrary() {
  return {
    version: TABLES_VERSION,
    tables: STARTER_TABLES.map((t) => newTable(t)),
    activeTableId: null,
    history: [],
  }
}

export function migrateLibrary(value) {
  if (!value || typeof value !== 'object') return emptyLibrary()
  const tables = Array.isArray(value.tables)
    ? value.tables.map((t) => ({
        id: t.id ?? uuid(),
        name: typeof t.name === 'string' ? t.name : 'Table',
        description: typeof t.description === 'string' ? t.description : '',
        entries: Array.isArray(t.entries) && t.entries.length > 0
          ? t.entries.map((e) => ({
              id: e.id ?? uuid(),
              text: typeof e.text === 'string' ? e.text : '',
              weight: clampWeight(e.weight ?? 1),
            }))
          : [newEntry()],
      }))
    : []
  return {
    version: TABLES_VERSION,
    tables,
    activeTableId:
      tables.find((t) => t.id === value.activeTableId)?.id ??
      tables[0]?.id ??
      null,
    history: Array.isArray(value.history) ? value.history.slice(0, MAX_HISTORY) : [],
  }
}

export function rollTable(table) {
  // Filter out empty-text entries before rolling so blank rows aren't
  // hit as a valid result.
  const usable = table.entries.filter((e) => e.text.trim() && e.weight > 0)
  if (usable.length === 0) return null
  const total = usable.reduce((s, e) => s + e.weight, 0)
  let r = Math.random() * total
  for (const e of usable) {
    r -= e.weight
    if (r <= 0) return e
  }
  return usable[usable.length - 1]
}

export function addHistoryEntry(library, tableId, tableName, entry) {
  const item = {
    id: uuid(),
    at: Date.now(),
    tableId,
    tableName,
    text: entry.text,
  }
  return { ...library, history: [item, ...library.history].slice(0, MAX_HISTORY) }
}

// Adds every STARTER_TABLES entry that the library doesn't already have
// by name (case-insensitive). Returns { library, addedCount }.
export function applyStarterPack(library) {
  const existing = new Set(
    library.tables.map((t) => t.name.trim().toLowerCase()),
  )
  const additions = STARTER_TABLES.filter(
    (t) => !existing.has(t.name.toLowerCase()),
  ).map((t) => newTable(t))
  return {
    library: { ...library, tables: [...library.tables, ...additions] },
    addedCount: additions.length,
  }
}

/* ---------- Export / Import ---------- */
function safeFilename(name) {
  return (name || 'table').replace(/[^a-z0-9-_ ]/gi, '_').trim() || 'table'
}

function triggerDownload(payload, filename) {
  const blob = new Blob([JSON.stringify(payload, null, 2)], {
    type: 'application/json',
  })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function downloadTableJson(table) {
  triggerDownload(
    { kind: 'randomTable', version: TABLES_VERSION, table },
    `${safeFilename(table.name)}.table.json`,
  )
}

export function downloadLibraryJson(library) {
  triggerDownload(library, 'tables-library.json')
}

function normalizeTableForImport(t) {
  return {
    id: uuid(),
    name: typeof t.name === 'string' && t.name ? t.name : 'Imported table',
    description: typeof t.description === 'string' ? t.description : '',
    entries:
      Array.isArray(t.entries) && t.entries.length > 0
        ? t.entries.map((e) => ({
            id: uuid(),
            text: typeof e.text === 'string' ? e.text : '',
            weight: clampWeight(e.weight ?? 1),
          }))
        : [newEntry()],
  }
}

// Returns { kind: 'table', table } or { kind: 'library', library }.
export function readJsonFile(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => {
      try {
        const parsed = JSON.parse(reader.result)
        if (!parsed || typeof parsed !== 'object') {
          reject(new Error('File is not valid JSON.'))
          return
        }
        if (parsed.kind === 'randomTable' && parsed.table) {
          resolve({ kind: 'table', table: normalizeTableForImport(parsed.table) })
          return
        }
        if (Array.isArray(parsed.tables)) {
          resolve({ kind: 'library', library: migrateLibrary(parsed) })
          return
        }
        reject(new Error('File does not look like a tables export.'))
      } catch (err) {
        reject(err)
      }
    }
    reader.onerror = () => reject(reader.error)
    reader.readAsText(file)
  })
}
